version: '3.8'

services:
  web:
    build: .
    image: ${DOCKER_HUB_USER:-genetic}/timetable-web:latest
    command: gunicorn colegio.wsgi:application --bind 0.0.0.0:8000 --access-logfile - --error-logfile - --log-level info
    volumes:
      - .:/app
    expose:
      - 8000
    environment:
      - DJANGO_DEBUG=False
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DB_ENGINE=django.db.backends.sqlite3
      - ENABLE_HTTPS=True
      - CSRF_TRUSTED_ORIGINS=https://localhost,https://52.14.216.149
      - ALLOWED_HOSTS=localhost,127.0.0.1,52.14.216.149
      - ADMIN_URL=gestion-secreta/
      - DJANGO_SECRET_KEY=django-insecure-super-secret-key-change-me-in-prod-please-12345
    depends_on:
      - redis

  celery:
    build: .
    image: ${DOCKER_HUB_USER:-genetic}/timetable-celery:latest
    command: celery -A colegio worker -l info
    volumes:
      - .:/app
    environment:
      - DJANGO_DEBUG=False
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DB_ENGINE=django.db.backends.sqlite3
      - C_FORCE_ROOT=1
    depends_on:
      - redis
      - web

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
      - .:/app
    depends_on:
      - web

  redis:
    image: redis:7-alpine